export default function Disclaimer() {
  return (
    <div className="min-h-screen bg-gray-50">
      <div className="max-w-4xl mx-auto px-6 py-12">
        <h1 className="text-3xl font-bold text-gray-900 mb-8">Disclaimer</h1>

        <div className="bg-white p-8 rounded-lg shadow-sm">
          <div className="prose prose-gray max-w-none">
            <p className="text-gray-600 mb-6">
              <strong>Last updated:</strong> {new Date().toLocaleDateString()}
            </p>

            <h2 className="text-2xl font-semibold text-gray-900 mb-4">General Disclaimer</h2>
            <p className="text-gray-700 mb-4">
              The information provided by this Cubic Yard Calculator is for general informational purposes only.
              All information on the site is provided in good faith, however we make no representation or warranty
              of any kind, express or implied, regarding the accuracy, adequacy, validity, reliability, availability,
              or completeness of any information on the site.
            </p>

            <h2 className="text-2xl font-semibold text-gray-900 mb-4">Calculation Accuracy</h2>
            <p className="text-gray-700 mb-4">
              While we strive to provide accurate calculations, the results generated by our calculator are estimates
              only. Actual material requirements may vary based on:
            </p>
            <ul className="list-disc list-inside text-gray-700 mb-4 space-y-2">
              <li>Material density variations</li>
              <li>Site conditions and soil composition</li>
              <li>Weather and moisture conditions</li>
              <li>Compaction and settling factors</li>
              <li>Construction methods and equipment</li>
            </ul>

            <h2 className="text-2xl font-semibold text-gray-900 mb-4">Professional Consultation</h2>
            <p className="text-gray-700 mb-4">
              This calculator is not a substitute for professional engineering advice, architectural consultation,
              or construction expertise. Always consult with qualified professionals for critical construction
              projects, large-scale earthwork, or complex engineering requirements.
            </p>

            <h2 className="text-2xl font-semibold text-gray-900 mb-4">No Liability</h2>
            <p className="text-gray-700 mb-4">
              Under no circumstance shall we have any liability to you for any loss or damage of any kind incurred
              as a result of the use of the site or reliance on any information provided on the site. Your use
              of the site and your reliance on any information on the site is solely at your own risk.
            </p>

            <h2 className="text-2xl font-semibold text-gray-900 mb-4">External Links</h2>
            <p className="text-gray-700 mb-4">
              The site may contain links to other websites or content belonging to or originating from third parties
              or links to websites and features in banners or other advertising. Such external links are not
              investigated, monitored, or checked for accuracy, adequacy, validity, reliability, availability,
              or completeness by us.
            </p>

            <div className="mt-8 p-4 bg-yellow-50 border-l-4 border-yellow-400">
              <p className="text-yellow-800 text-sm">
                <strong>Important:</strong> This calculator provides estimates for planning purposes only.
                Always verify calculations with on-site measurements and consult local building codes and regulations.
              </p>
            </div>
          </div>
        </div>
      </div>

      {/* Footer */}
      <footer className="bg-gray-900 text-white py-8">
        <div className="max-w-6xl mx-auto px-6">
          <div className="grid grid-cols-1 md:grid-cols-5 gap-8">
            <div>
              <h3 className="font-semibold mb-4">Calculators</h3>
              <ul className="space-y-2 text-sm">
                <li><a href="/" className="hover:text-blue-300">General Calculator</a></li>
                <li><a href="/gravel-calculator" className="hover:text-blue-300">Gravel Calculator</a></li>
                <li><a href="/concrete-calculator" className="hover:text-blue-300">Concrete Calculator</a></li>
                <li><a href="/topsoil-and-mulch-calculator" className="hover:text-blue-300">Topsoil Calculator</a></li>
                <li><a href="/earthwork-calculator" className="hover:text-blue-300">Earthwork Calculator</a></li>
              </ul>
            </div>
            <div>
              <h3 className="font-semibold mb-4">Conversions</h3>
              <ul className="space-y-2 text-sm">
                <li><a href="/conversions/cubic-yards-to-tons" className="hover:text-blue-300">Cubic Yards to Tons</a></li>
                <li><a href="/conversions/square-feet-to-cubic-yards" className="hover:text-blue-300">Square Feet to Cubic Yards</a></li>
              </ul>
            </div>
            <div>
              <h3 className="font-semibold mb-4">Material Types</h3>
              <ul className="space-y-2 text-sm">
                <li>Gravel & Crushed Stone</li>
                <li>Sand & Aggregates</li>
                <li>Topsoil & Soil</li>
                <li>Concrete & Cement</li>
                <li>Mulch & Organics</li>
              </ul>
            </div>
            <div>
              <h3 className="font-semibold mb-4">Professional Tools</h3>
              <ul className="space-y-2 text-sm">
                <li>Multi-Area Projects</li>
                <li>Earthwork Calculations</li>
                <li>Cost Estimation</li>
                <li>Material Density Factors</li>
              </ul>
            </div>
            <div>
              <h3 className="font-semibold mb-4">Company</h3>
              <ul className="space-y-2 text-sm">
                <li><a href="/about-us" className="hover:text-blue-300">About Us</a></li>
                <li><a href="/contact-us" className="hover:text-blue-300">Contact Us</a></li>
                <li><a href="/privacy-policy" className="hover:text-blue-300">Privacy Policy</a></li>
                <li><a href="/terms-and-conditions" className="hover:text-blue-300">Terms and Conditions</a></li>
                <li><a href="/disclaimer" className="hover:text-blue-300">Disclaimer</a></li>
              </ul>
            </div>
          </div>
          <div className="border-t border-gray-800 mt-8 pt-8 text-center text-sm text-gray-400">
            <p>Professional cubic yard calculator for accurate construction and landscaping estimates.</p>
          </div>
        </div>
      </footer>
    </div>
  );
}
